"""Add pdf_downloaded column

Revision ID: 664239292e5e
Revises: 91a2ece4c254
Create Date: 2025-02-07 22:29:39.655542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664239292e5e'
down_revision: Union[str, None] = '91a2ece4c254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('pdf_downloaded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'pdf_downloaded')
    # ### end Alembic commands ###
