"""Add DOI and article_chunks

Revision ID: 91a2ece4c254
Revises: 64410a3df432
Create Date: 2025-02-07 22:21:16.536271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a2ece4c254'
down_revision: Union[str, None] = '64410a3df432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_chunks_id'), 'article_chunks', ['id'], unique=False)
    op.add_column('articles', sa.Column('doi', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'doi')
    op.drop_index(op.f('ix_article_chunks_id'), table_name='article_chunks')
    op.drop_table('article_chunks')
    # ### end Alembic commands ###
